DOWNLOAD_TAG_VER: v3.7.0
META:
  TITLE: TrippyHippy
  AUTHOR: TrippyHippy
  DESCRIPTION: Avid Gamer, GTAV Glitcher, Outfit Building noob, Account creator.
  ICON_URL: favicon.jpg
  THEME: dark
BIO:
  ICON_URL: icon.jpg
  TITLE: TrippyHippy
  DESCRIPTION: Avid Gamer, GTAV Glitcher, Outfit Building noob, Account creator.
  FOOTER: Like and Subscribe!
BASE_SHORT_URL: ""
ENABLE_REDIRECTS: true
LINKS:
  - brand: youtube
    icon: youtube
    name: YouTube
    link: /youtube
    redirects:
      - src: /youtube
        dest: https://www.youtube.com/@Trippy_Hippy89
        code: 308
      - src: /yt
        dest: https://www.youtube.com/@Trippy_Hippy89
        code: 308
  - brand: discord
    icon: discord
    name: Discord
    link: /discord
    redirects:
      - src: /discord
        dest: https://discord.gg/uptRxyTP
        code: 308
